name = "pluto"
type = "javascript"
main = "dist/index.html"

[env.production]
routes = [
  { pattern = "www.thepluto.org", zone_name = "thepluto.org" },
  { pattern = "thepluto.org", zone_name = "thepluto.org" }
]

[build]
command = "npm run build"
cwd = "./dist"
watch_paths = ["src/**/*.tsx", "src/**/*.ts"]

[[routes]]
pattern = "/*"
custom_domain = false
