// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjpbbnmxfuuaevwotsfh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qcGJibm14ZnV1YWV2d290c2ZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NDM5MTMsImV4cCI6MjA3MDQxOTkxM30.nVGuN1mir_jkfUk4zm492yzguQe5JH6JMw_MAYaTdrs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});